import { all } from "redux-saga/effects";
import {
  registrationWatcher,
  loginWatcher,
  logoutWatcher,
  forgotPasswordWatcher,
  resetPasswordWatcher,
  verifyTokenWatcher,
  resendEmailVerificationWatcher,
  countryListWatcher,
} from "../duck/auth/auth.saga";

import {
  addContactWatcher,
  listContactWatcher,
  deleteContactWatcher,
  getContactByIdWatcher,
  updateContactWatcher,
  addContactNoteWatcher,
  listContactNoteWatcher,
  deleteContactNoteWatcher,
  updateContactNoteWatcher,
  addContactTaskWatcher,
  contactImportWatcher,
  listContactTaskWatcher,
  deleteContactTaskWatcher,
  updateContactTaskWatcher,
  appointmentListWatcher,
  getAllGmailMessagesByContactEmailWatcher,
  getContactGmailMessagesByIdWatcher,
} from "../duck/contact/contact.saga";

import {
  addBookingWatcher,
  listBookingsWatcher,
  deleteBookingWatcher,
  getBookingByIdWatcher,
  updateBookingWatcher,
  addBookingNoteWatcher,
  listBookingNoteWatcher,
  deleteBookingNoteWatcher,
  updateBookingNoteWatcher,
  addBookingTaskWatcher,
  listBookingTaskWatcher,
  deleteBookingTaskWatcher,
  updateBookingTaskWatcher,
  createAppointmentWatcher,
  bookingListViewWatcher,
  deleteAppointmentWatcher,
  updateAppointmentWatcher,
  createBookingPaymentWatcher,
} from "../duck/booking/booking.saga";

import {
  addServiceWatcher,
  listServiceWithSourceWatcher,
  addSourceWatcher,
  listLeadStatusWatcher,
  addLeadWatcher,
  getLeadByIdWatcher,
  deleteLeadWatcher,
  updateLeadWatcher,
  addLeadNoteWatcher,
  listLeadNoteWatcher,
  updateLeadNoteWatcher,
  deleteLeadNoteWatcher,
  listLeadWatcher,
  addLeadTaskWatcher,
  updateLeadTaskWatcher,
  deleteLeadTaskWatcher,
  listLeadTaskWatcher,
  updateLeadStatusWatcher,
  listLeadWithPositionWatcher,
  markLeadStatusWatcher,
  listLostReasonWatcher,
  addLostReasonWatcher,
  getAllCompletedLeadsWatcher,
  customizeLeadStageWatcher,
  getAllGmailMessagesByLeadEmailWatcher,
  getGmailMessagesByIdWatcher,
} from "../duck/lead/lead.saga";

import {
  getProfileDetailWatcher,
  updateOwnerProfileDetailWatcher,
  updatePasswordWatcher,
  updateBusinessProfileDetailWatcher,
  getMenuCountWatcher,
  connectWithPaypalWatcher,
  makeTestPaymentWatcher,
  deletePaymentAccountWatcher,
  getSubscriptionPlanWatcher,
  createSubscriptionPlanWatcher,
  planApplyCouponWatcher,
  getStateTaxWatcher,
  updateSubscriptionPlanWatcher,
  cancelSubscriptionPlanWatcher,
  addProfileServiceWatcher,
  deleteAllDummyDataRequestWatcher,
  getStateWatcher,
  updateAutoReplyDataWatcher,
  getAutoReplyDataWatcher,
} from "../duck/profile/profile.saga";

import {
  addDashboardTaskWatcher,
  updateDashboardTaskWatcher,
  listDashboardTaskWatcher,
  deleteDashboardTaskWatcher,
  getBusinessSnapshotWatcher,
  listDashboardNotificationWatcher,
  deleteDashboardNotificationWatcher,
  deleteAllNotificationWatcher,
  markAsReadNotificationWatcher,
  userLoginStatusWatcher,
} from "../duck/dashboard/dashboard.saga";

import {
  listQuoteWatcher,
  addQuoteWatcher,
  addQuoteTemplateWatcher,
  getQuoteTemplateByIdWatcher,
  getQuoteByIdWatcher,
  updateQuoteCustomerWatcher,
  updateQuoteWatcher,
  sendToCustomerQuoteWatcher,
  viewCustomerQuoteWatcher,
  changeQuoteStatusWatcher,
  reviseQuoteWatcher,
  getAcceptedQuoteWatcher,
  deleteQuoteWatcher,
  listQuoteTemplateWatcher,
  updateBasicQuoteWatcher,
  updateMessageBodyQuoteWatcher,
  getMessageBodyQuoteWatcher,
} from "../duck/quote/quote.saga";

import {
  listInvoiceWatcher,
  addInvoiceWatcher,
  getInvoiceByIdWatcher,
  updateInvoiceWatcher,
  sendToCustomerInvoiceWatcher,
  viewCustomerInvoiceWatcher,
  markPaidInvoiceWatcher,
  invoiceMakePaymentWatcher,
  getPaidInvoiceWatcher,
  deleteInvoiceWatcher,
  updateBasicInvoiceWatcher,
  listInvoiceTemplateWatcher,
  addInvoiceTemplateWatcher,
  getInvoiceTemplateByIdWatcher,
  getMessageBodyInvoiceWatcher,
  updateMessageBodyInvoiceWatcher,
} from "../duck/invoice/invoice.saga";

import { contactUsFormWatcher } from "../duck/website/website.saga";

import {
  getGmailAuthLinkWatcher,
  getGmailAuthTokenWatcher,
  getGmailValidTokenWatcher,
  getAllGmailMessagesWatcher,
  getGmailMessageWatcher,
  deleteGmailMessageWatcher,
  modifyGmailMessageWatcher,
  getGmailMessageByIdWatcher,
  sendGmailMessageWatcher,
  sendGmailMessageWithAttachmentWatcher,
  getGmailMessageAttachmentByIdWatcher,
  resetEmailStateWatcher,
  setGmailMessageWatcher,
  getAllDraftGmailMessagesWatcher,
  getDraftGmailMessageByIdWatcher,
  getDraftGmailMessageWatcher,
  createDraftGmailMessageWatcher,
  deleteDraftGmailMessageWatcher,
  markGmailMessageAsUnreadWatcher,
  markGmailMessageAsTrashWatcher,
  markGmailMessageAsSpamWatcher,
  markGmailMessageAsInboxWatcher,
  saveSocialAuthTokenWatcher,
  updateDraftGmailMessageWatcher,
} from "../duck/email/email.saga";

import {
  getCalendarEventListWatcher,
  deleteCalendarEventListWatcher,
  editCalendarEventListWatcher,
} from "../duck/calendar/calendar.saga"

export function* rootSaga() {
  yield all([
    registrationWatcher(),
    loginWatcher(),
    logoutWatcher(),
    forgotPasswordWatcher(),
    countryListWatcher(),
    resetPasswordWatcher(),
    verifyTokenWatcher(),
    addContactWatcher(),
    listContactWatcher(),
    deleteContactWatcher(),
    getContactByIdWatcher(),
    updateContactWatcher(),
    addContactNoteWatcher(),
    listContactNoteWatcher(),
    deleteContactNoteWatcher(),
    updateContactNoteWatcher(),
    addContactTaskWatcher(),
    contactImportWatcher(),
    listContactTaskWatcher(),
    deleteContactTaskWatcher(),
    updateContactTaskWatcher(),
    resendEmailVerificationWatcher(),
    addBookingWatcher(),
    listBookingsWatcher(),
    deleteBookingWatcher(),
    getBookingByIdWatcher(),
    updateBookingWatcher(),
    addServiceWatcher(),
    addSourceWatcher(),
    addLeadWatcher(),
    listServiceWithSourceWatcher(),
    listLeadStatusWatcher(),
    getLeadByIdWatcher(),
    deleteLeadWatcher(),
    updateLeadWatcher(),
    addLeadNoteWatcher(),
    listLeadNoteWatcher(),
    updateLeadNoteWatcher(),
    deleteLeadNoteWatcher(),
    listLeadWatcher(),
    addLeadTaskWatcher(),
    updateLeadTaskWatcher(),
    deleteLeadTaskWatcher(),
    listLeadTaskWatcher(),
    updateLeadStatusWatcher(),
    listLeadWithPositionWatcher(),
    markLeadStatusWatcher(),
    listLostReasonWatcher(),
    addLostReasonWatcher(),
    getAllCompletedLeadsWatcher(),
    customizeLeadStageWatcher(),
    addBookingNoteWatcher(),
    listBookingNoteWatcher(),
    deleteBookingNoteWatcher(),
    updateBookingNoteWatcher(),
    addBookingTaskWatcher(),
    listBookingTaskWatcher(),
    deleteBookingTaskWatcher(),
    updateBookingTaskWatcher(),
    getProfileDetailWatcher(),
    updateOwnerProfileDetailWatcher(),
    updatePasswordWatcher(),
    updateBusinessProfileDetailWatcher(),
    addDashboardTaskWatcher(),
    updateDashboardTaskWatcher(),
    listDashboardTaskWatcher(),
    deleteDashboardTaskWatcher(),
    getBusinessSnapshotWatcher(),
    listDashboardNotificationWatcher(),
    deleteDashboardNotificationWatcher(),
    deleteAllNotificationWatcher(),
    markAsReadNotificationWatcher(),
    getMenuCountWatcher(),
    listQuoteWatcher(),
    addQuoteWatcher(),
    addQuoteTemplateWatcher(),
    getQuoteTemplateByIdWatcher(),
    getQuoteByIdWatcher(),
    updateQuoteCustomerWatcher(),
    updateQuoteWatcher(),
    sendToCustomerQuoteWatcher(),
    viewCustomerQuoteWatcher(),
    changeQuoteStatusWatcher(),
    reviseQuoteWatcher(),
    getAcceptedQuoteWatcher(),
    deleteQuoteWatcher(),
    listQuoteTemplateWatcher(),
    updateBasicQuoteWatcher(),
    connectWithPaypalWatcher(),
    makeTestPaymentWatcher(),
    addInvoiceWatcher(),
    listInvoiceWatcher(),
    getInvoiceByIdWatcher(),
    updateInvoiceWatcher(),
    sendToCustomerInvoiceWatcher(),
    viewCustomerInvoiceWatcher(),
    markPaidInvoiceWatcher(),
    invoiceMakePaymentWatcher(),
    getPaidInvoiceWatcher(),
    deleteInvoiceWatcher(),
    updateBasicInvoiceWatcher(),
    listInvoiceTemplateWatcher(),
    addInvoiceTemplateWatcher(),
    getInvoiceTemplateByIdWatcher(),
    contactUsFormWatcher(),
    deletePaymentAccountWatcher(),
    userLoginStatusWatcher(),
    getSubscriptionPlanWatcher(),
    createSubscriptionPlanWatcher(),
    planApplyCouponWatcher(),
    getStateTaxWatcher(),
    updateSubscriptionPlanWatcher(),
    cancelSubscriptionPlanWatcher(),
    addProfileServiceWatcher(),
    createAppointmentWatcher(),
    bookingListViewWatcher(),
    deleteAppointmentWatcher(),
    updateAppointmentWatcher(),
    appointmentListWatcher(),
    deleteAllDummyDataRequestWatcher(),
    createBookingPaymentWatcher(),
    getStateWatcher(),
    updateMessageBodyQuoteWatcher(),
    getMessageBodyQuoteWatcher(),
    getMessageBodyInvoiceWatcher(),
    updateMessageBodyInvoiceWatcher(),
    updateAutoReplyDataWatcher(),
    getAutoReplyDataWatcher(),
    getGmailAuthLinkWatcher(),
    getGmailAuthTokenWatcher(),
    getGmailValidTokenWatcher(),
    getAllGmailMessagesWatcher(),
    getGmailMessageWatcher(),
    deleteGmailMessageWatcher(),
    modifyGmailMessageWatcher(),
    getGmailMessageByIdWatcher(),
    sendGmailMessageWatcher(),
    sendGmailMessageWithAttachmentWatcher(),
    getGmailMessageAttachmentByIdWatcher(),
    resetEmailStateWatcher(),
    setGmailMessageWatcher(),
    getAllDraftGmailMessagesWatcher(),
    getDraftGmailMessageWatcher(),
    getDraftGmailMessageByIdWatcher(),
    createDraftGmailMessageWatcher(),
    deleteDraftGmailMessageWatcher(),
    markGmailMessageAsUnreadWatcher(),
    markGmailMessageAsTrashWatcher(),
    markGmailMessageAsSpamWatcher(),
    markGmailMessageAsInboxWatcher(),
    saveSocialAuthTokenWatcher(),
    updateDraftGmailMessageWatcher(),
    getCalendarEventListWatcher(),
    deleteCalendarEventListWatcher(),
    editCalendarEventListWatcher(),
    getAllGmailMessagesByLeadEmailWatcher(),
    getGmailMessagesByIdWatcher(),
    getAllGmailMessagesByContactEmailWatcher(),
    getContactGmailMessagesByIdWatcher(),
  ]);
}
